<?php

namespace common\models;

use yii\helpers\Url;
use Yii;
use common\models\Adminuser;
use yii\web\Link;
use yii\web\linkable;

/**
 * This is the model class for table "article".
 *
 * @property int $id ID
 * @property string $title 标题
 * @property string $content 内容
 * @property int $category_id 分类
 * @property int $status 状态
 * @property int $created_by 创建人
 * @property int $created_at 创建时间
 * @property int $updated_at 最后修改时间
 *
 * @property Adminuser $createdBy
 */
class Article extends \yii\db\ActiveRecord implements Linkable
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'article';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'content'], 'required'],
            [['content'], 'string'],
            [['category_id', 'status', 'created_by', 'created_at', 'updated_at'], 'integer'],
            [['title'], 'string', 'max' => 512],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => Adminuser::className(), 'targetAttribute' => ['created_by' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'content' => 'Content',
            'category_id' => 'Category ID',
            'status' => 'Status',
            'created_by' => 'Created By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }
    public function getLinks()
    {
        // TODO: Implement getLinks() method.
        return [
            Link::REL_SELF=>Url::to(['article/view','id'=>$this->id,true])
        ];
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($insert) {
                $this->created_at = time();
                $this->updated_at = time();
                $this->created_by = 1;//Yii::$app->user->identity->id;
            } else {
                $this->updated_at = time();
            }

            return true;

        } else {
            return false;
        }
    }

//    public function fields()  //指定字段
//    {
////        return [
////            'id',
////            'title',
////            'content_title' => 'content', //自定义字段名
////            'status',
////            'status_text' => function ($model) {  //通过匿名函数指定
////                return $model->status == 1 ? '已发布' : '未发布';
////            },
//////            'createdBy' => function ($model) {
//////                return $model->createdBy->realname;  //如果这里出现Trying to get property of non-object,可能是关联字段查出来的值是空
//////            }
////        ]; // TODO: Change the autogenerated stub
//        $fields = parent::fields();
//        unset($fields['title']);
//        return $fields;
//    }
//
//    public function extraFields()
//    {
//        return ['createdBy']; // TODO: Change the autogenerated stub   //扩展字段  调用接口http://advanced.com/api.php/articles?expand=createdBy
//        //如果不想更改前端的调用地址,可以修改main.php的urlManager
//        /*        'rules' => [
//                [
//                    'class'=>'yii\rest\UrlRule',
//                    'controller'=>'article',
//                    'ruleConfig'=>[
//                        'class'=>'yii\web\urlRule',
//                        'defaults'=>[
//                            'expand'=>'createdBy'
//                        ]
//                    ]
//                ]
//            ],*/
//    }



    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(Adminuser::className(), ['id' => 'created_by']);
    }
}
