<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/5/27 0027
 * Time: 14:53
 */

namespace api\controllers;

use common\models\Adminuser;
use common\models\Article;
use yii\data\ActiveDataProvider;
use yii\filters\auth\HttpBasicAuth;
use yii\filters\auth\QueryParamAuth;
use yii\helpers\ArrayHelper;
use yii\rest\ActiveController;

class ArticleController extends ActiveController
{
    public $modelClass = 'common\models\Article';

    //分页的实现
    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['index']);
        return $actions;
    }

    //认证状态--方式一.请求参数
    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            'authenticator' => [
                'class' => QueryParamAuth::className()
            ]
        ]);
    }
    //认证状态--方式二.HTTP基本认知
    /*    public function behaviors()
        {
            return ArrayHelper::merge(parent::behaviors(), [
                'authenticator' => [
                    'class' => HttpBasicAuth::className(),
                    'auth' => function ($username, $password) {
                        $user=Adminuser::find()->where(['username'=>$username])->one();
                        if($user->validatePassword($password)){
                            return $user;
                        }
                        return null;
                    }
                ]
            ]);
        }*/

    public function actionIndex()
    {
        $modelClass = $this->modelClass;
        return new ActiveDataProvider([
            'query' => $modelClass::find()->asArray(),
            'pagination' => ['pageSize' => 5]
        ]);
    }

    //关键词搜索
    public function actionSearch()
    {
        $keyword = $_POST['key_word'];
        return Article::find()->where(['like', 'content', $keyword])->asArray()->all();
    }


}