<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/5/27 0027
 * Time: 14:53
 */

namespace api\controllers;

use common\models\Article;
use yii\data\ActiveDataProvider;
use yii\rest\ActiveController;

class ArticleController extends ActiveController
{
    public $modelClass = 'common\models\Article';

    //分页的实现
    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['index']);
        return $actions;
    }

    public function actionIndex()
    {
        $modelClass = $this->modelClass;
        return new ActiveDataProvider([
            'query' => $modelClass::find()->asArray(),
            'pagination' => ['pageSize' => 5]
        ]);
    }

    //关键词搜索
    public function actionSearch()
    {
        $keyword = $_POST['key_word'];
        return Article::find()->where(['like', 'content', $keyword])->asArray()->all();
    }



}